### ISSUE TITLE
Implement compile command

### ISSUE THREAD

**Issue by cntkillme** [RSA-Internal/PandaProtector#1]
TODO
- [x] Update wandbox to include `fromStringv2`
- [x] Create a type definition for it
- [x] Decide on a list of languages to show in the compile command description

**Comment by TinyPandas** [comment]
Completed type definition in [Merge pull request #1 from TinyPandas/develop](https://github.com/TinyPandas/node-wandbox-api/commit/9f93df29795e650713ae9ce2c6a0d1291f771441)

**Comment by TinyPandas** [comment]
The checklist above is completed. Currently working on a `compile compilers [language]` option to list languages and versions, along side their compiler name.

**Comment by cntkillme** [comment]
Closed, tracking in #31
