### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by Det2x** [RSA-Internal/PandaProtector#13]
Dependabot creates pull requests to keep your dependencies secure and up-to-date. This could be very beneficial considering you wouldn't have to manually update everything.

https://dependabot.com/

**Comment by TinyPandas** [comment]
Does this update the `package.json` or the actual dependency within `node_modules`?

If it is the latter, than I feel providing `^` within the version specified in `package.json` is sufficient enough for this to not be implemented. We currently have the bot running `npm i` before starting upon an update, so it helps ensure that the live build has most up-to-date dependencies.

Within our dev environments, we follow the same steps, making sure everything lines up.

**Comment by cntkillme** [comment]
It updates the former to keep dependencies up to date. I don't think it's that much of an issue but it could help prevent merge conflicts from people accidentally committing their package.json changes after updating.

**Comment by cntkillme** [comment]
@Dicey95 after a bit more consideration I think this is a good idea, a PR is welcome but otherwise I will get to it eventually.
