### ISSUE TITLE
Transition to slash commands

### ISSUE THREAD

**Issue by cntkillme** [RSA-Internal/PandaProtector#3]
Currently, discord.js does not support slash commands so a custom command parser is provided. When discord.js supports slash commands, use it instead.

**Comment by TinyPandas** [comment]
Utilize ephemeral (only the executor can see results) outside of setting defined channel.
Have secondary setting for global-ephemeral (default: false) - Controls above action

**Comment by TinyPandas** [comment]
205e44a
