### ISSUE TITLE
List of supported languages

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Internal/PandaProtector#31]

**Comment by cntkillme** [comment]
This is done with `;compile langs`, if more needs to be done the issue can be reopened.

**Comment by cntkillme** [comment]
I think `;compile` and `;compile langs` should be separate commands, it is a pretty awkward to treat command parameters differently depending on a previous parameter. I propose `;compile` to handle compiling and executing a language, and `;compilers [lang]` to query for compilers given a lang (and show a default set of langs + compilers as per the original issue).

**Comment by TinyPandas** [comment]
#39
