### ISSUE TITLE
Update to djs beta

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Internal/PandaProtector#35]
Update to their beta (or whatever it be called) of v13, to incorporate usability of "pending" field on a member for entry, and slash commands.

**Comment by cntkillme** [comment]
Does the beta support the "reply to message" feature.

**Comment by TinyPandas** [comment]
https://discord.js.org/#/docs/main/master/class/Message?scrollTo=reply

If this is what you are referring to, then yes.

**Comment by cntkillme** [comment]
No, this feature: ![image](https://user-images.githubusercontent.com/12593019/118419176-2a778380-b670-11eb-9d34-a8b5fe25842b.png)

**Comment by TinyPandas** [comment]
Current impl of report is broken
Current impl of ping is broken

Remaining commands untested
