### ISSUE TITLE
Have github take plural version of first param

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Internal/PandaProtector#63]
Taking a plural type (ie: issues, or branches) would list available items on the provided repo.

**Comment by cntkillme** [comment]
With the `choices` feature, I don't think you'd need to bother with plural choices or different names for the same option (e.g., no more repo **and** repository)

**Comment by TinyPandas** [comment]
It's not meant as that. Its an additive.

So like for example, we have `/github branch {branchName}`, which would list that branch.. what I'm looking to implement would be `/github branches` which would list all available branches.

Could just make the `query` param optional, and if it's not provided, then fullfil the same result.

**Comment by cntkillme** [comment]
Oh, yeah I think making the query param optional is more inline with the other commands in how they work.

**Comment by TinyPandas** [comment]
I'll look into it after we clean up what we have. Don't want too many hands on the same file. 😂

It'll probably be later this week though.

**Comment by TinyPandas** [comment]
Have decided against this for the time being. There's not enough interest in the github command to implement further features at this time.
