### ISSUE TITLE
Cache Command[] for getCommands

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Internal/PandaProtector#66]

**Comment by TinyPandas** [comment]
Potentially cache the ids from the slash-commands on loading, and store them outside of the bot in event of a crash. This way the bot does not have to regenerate the commands on each startup.

More details on duration of id cache later.

**Comment by TinyPandas** [comment]
Bot does not restart often enough to worry about caching the slash-command ids. Carry on with what you were looking to implement! :D

**Comment by cntkillme** [comment]
With the implementation of slash commands, the `help` command is made pretty much useless which is really what this issue was mostly for. If we are not caching the IDs and we no longer need to cache the result of `getCommands` this issue can be closed.
