### ISSUE TITLE
Use Command Permissions

### ISSUE THREAD

**Issue by cntkillme** [RSA-Internal/PandaProtector#86]
Currently, if a user uses a command they do not have permission to the interaction just fails. Switch to using the native interaction permissions over the custom handled permissions currently being used.

This is a BREAKING CHANGE, the `hasPermission` field will be removed from the `Command` interface.

**Comment by TinyPandas** [comment]
Began work on the feature/permissions branch

- Current barriers: Commands attempted to index `state` before being set. Implemented a sort of work-around with `store/permissions.ts`. The idea is it has a backup field in the event of index state before being defined, then reads from the config directly instead.

**Comment by TinyPandas** [comment]
#91
