### ISSUE TITLE
Exithook does not properly unload slash-commands

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Internal/PandaProtector#92]
```ts
	// Cleanup resources on exit.
	exitHook(() => {
		client.guilds.cache.get(config.guildId)?.commands.set([]).catch(console.error.bind(console));
		disconnect().catch(console.error.bind(console));
	});
```

While this code does catch on bot shutdown, or `Ctrl + C` within testing, it does not present unloading of the slash-commands.

### Ways this was tested
```ts
	exitHook(() => {
		client.guilds.cache
			.get(config.guildId)
			?.commands.set([])
			.then(() => console.log("Successfully unloaded slash-commands."))
			.catch(console.error.bind(console));
		console.log("Exiting...");
	});
```

"Exiting..." prints, where "Successfully unloaded slash-commands" never does. The slash-commands are still relevant within discord after the bot has been shutdown, and persist even after client reload.

**Comment by cntkillme** [comment]
Might be because exit-hook doesn't support async. calls, so it exits when all the functions passed to exitHook terminate. I think replacing the dependency with async-exit-hook should fix this issue.

**Comment by TinyPandas** [comment]
Switching to `async-exit-hook` and testing via the following code (provided from their examples) still warrants lack of unloading slash-commands.

```ts
	exitHook(callback => {
		setTimeout(() => {
			client.guilds.cache
				.get(config.guildId)
				?.commands.set([])
				.then(console.log.bind(console))
				.catch(console.error.bind(console));
			callback();
		}, 50);

		console.log("Exiting.");
	});
```

**Comment by cntkillme** [comment]
you need to call the callback within `then` and `catch`

**Comment by TinyPandas** [comment]
Got it..

```ts
	exitHook(callback => {
		setTimeout(() => {
			client.guilds.cache.get(config.guildId)?.commands.set([]).then(callback).catch(console.error.bind(console));
		}, 50);

		console.log("Exiting.");
	});
```

unloaded successfully. Will push out later tonight.

**Comment by TinyPandas** [comment]
Do we even want this still, as we discovered last night that commands are cached, and don't need to be recreated to continue working?

**Comment by TinyPandas** [comment]
Closed: Will review again on refactor in favor of loading cached commands, and only unloading on removal of a command.
